force-app/main/default/objects/Case/fields/Tweet_Id__c.field-meta.xml
<CustomField>
    <fullName>Tweet_Id__c</fullName>
    <label>Post Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Post_Comments__c/Post_Comments__c.object-meta.xml
<CustomObject>
    <label>Post Comments</label>
    <nameField>
        <label>Post Comments Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Post Comments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Post_Comments__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Post Comments</relationshipLabel>
    <relationshipName>Post_Comments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Post_Comments__c/fields/Comment_Id__c.field-meta.xml
<CustomField>
    <fullName>Comment_Id__c</fullName>
    <label>Comment Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Post_Comments__c/fields/Replied_Comments__c.field-meta.xml
<CustomField>
    <fullName>Replied_Comments__c</fullName>
    <label>Replied Comments</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/classes/InstagramAuthHelperTest.cls
@isTest
public class InstagramAuthHelperTest {
    static testmethod void testsample(){  
        Case caseRec = new Case();
        caseRec.Tweet_Id__c = 'tweetId';
        insert caserec;
        
        Post_Comments__c postComment = new Post_Comments__c();
        postComment.Case__c= caserec.Id;
        postComment.Comment_Id__c = 'commentId';
        postComment.Replied_Comments__c = 'RepliesWrapper:[data=(ReplyData:[id=123, text=Test Reply 1, username=testuser1, timeStamp=2023-07-29T12:34:56+0000,Case__c=caseId])])';
		insert postComment;
        
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new InstagramAuthHelperTestMockTest());
        InstagramAuthHelper.getAllPostsFromInstaForUserId();
        Test.stopTest();
    }
    
    
    static testmethod void getHashtagIdFromInsta_test(){  
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new InstagramAuthHelperTestMockTest());
        InstagramAuthHelper.getHashtagIdFromInsta('INSTA');
        Test.stopTest();
    }
    
    static testmethod void getPostDetailsByHashTagId_test(){  
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new InstagramAuthHelperTestMockTest());
        InstagramAuthHelper.getPostDetailsByHashTagId('INSTA');
        Test.stopTest();
    }
    
    static testmethod void getAllDetailsOfMedia_test(){  
        Case caseRec = new Case();
        caseRec.Tweet_Id__c = 'tweetId';
        insert caserec;
        
        Post_Comments__c postComment = new Post_Comments__c();
        postComment.Case__c= caserec.Id;
        postComment.Comment_Id__c = 'commentId';
		insert postComment;
        
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new InstagramAuthHelperTestMockTest());
        InstagramAuthHelper.getAllDetailsOfMedia('INSTA');
        Test.stopTest();
    }
    
     static testmethod void testsamplelast(){  
        Case caseRec = new Case();
        caseRec.Tweet_Id__c = 'tweetId';
        insert caserec;
        
        Post_Comments__c postComment = new Post_Comments__c();
        postComment.Case__c= caserec.Id;
        postComment.Comment_Id__c = 'commentId';
        postComment.Replied_Comments__c = 'RepliesWrapper:[data=(ReplyData:[id=123, text=Test Reply 1, username=testuser1, timeStamp=2023-07-29T12:34:56+0000,Case__c=caseId])])';
		insert postComment;
        
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new InstagramAuthHelperTestMockTest());
        InstagramAuthHelper.getAllPostsFromInstaForUserIdDummy();
        Test.stopTest();
    }
    
    
    static testmethod void getAllDetailsOfComments_test(){  
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new InstagramAuthHelperTestMockTest());
        InstagramAuthHelper.getAllDetailsOfComments('INSTA');
        Test.stopTest();
    }
}